export const GET_PURCHASES = 'GET_PURCHASES'
export const GET_PURCHASES_SUCCESS = 'GET_PURCHASES_SUCCESS'
export const GET_PURCHASES_FAILED = 'GET_PURCHASES_FAILED'

export const REMOVE_PURCHASE = 'REMOVE_PURCHASE'
export const REMOVE_PURCHASE_SUCCESS = 'REMOVE_PURCHASE_SUCCESS'
export const REMOVE_PURCHASE_FAILED = 'REMOVE_PURCHASE_FAILED'


export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'